### ISSUE TITLE
new git tag

### ISSUE THREAD

**Issue by tehnick** [signalapp/libsignal-protocol-c#107]
It would be nice if you could add a new git tag in foreseeable future.

From packaging point of view current state of library in a master branch is much better than from last stable release. For example, git snapshots are used now in Debian and Ubuntu:
https://tracker.debian.org/pkg/libsignal-protocol-c
https://launchpad.net/ubuntu/+source/libsignal-protocol-c

And your library is used at least by two packages with different xmpp clients there:
https://tracker.debian.org/pkg/dino-im
https://tracker.debian.org/pkg/psi-plus

New git tag will simplify life for maintainers of Debian and other GNU/Linux distributions.

**Comment by florianlenz** [comment]
+1 I would like to pull it into my project. Currently I use the master branch ...

**Comment by toabctl** [comment]
+1

**Comment by Neustradamus** [comment]
+1

**Comment by toabctl** [comment]
@dkonigsberg is there a reason to not do a git tag? could you comment on this issue, please?

**Comment by dkonigsberg** [comment]
The reason I've been dragging my feet on a tag is that its not entirely obvious what tag to apply. Feature-wise, this library is no longer in lock-step with libsignal-protocol-java.  Some recent features from the Java library have not yet been ported over to this one (due to lack of demand), while other housekeeping changes have been ported over. Therefore, any updated version number won't be directly translatable to a version of the Java library.

Right now, I'm thinking the most sensible option will be to simply increment a minor part of the version number that doesn't actually match up against anything in the Java library's repo. That will hopefully make everyone happy, while not causing too much confusion.

**Comment by dkonigsberg** [comment]
Just tagged the latest code as v2.3.2 to make everyone happy.
I think the Java library is now published as something around v2.6.0 or newer, but they seem to have stopped actually applying Git tags after v2.3.0.
