### ISSUE TITLE
Using semver and bump 2.3.2 to 3.0.0 according to it

### ISSUE THREAD

**Issue by darix** [signalapp/libsignal-protocol-c#112]
2.3.2 introduced a breaking API change which is not a nice thing. semver would suggest that in this case the major version number should be bumped.

**Comment by dkonigsberg** [comment]
Will be kept in mind for future library changes.

**Comment by 32d42eee-2809-41ba-9876-72c2844fcb15** [comment]
For packaging, the soname of the library is important and the soname is typically taken from the major number. To get libsignal-protocol-c 2.3.2 into Debian, we need to bump the soname from 2 to 3,

@dkonigsberg Would you make the next major version bump directly from 2 to 4, so that Debian can use 3 for 2.3.2?

If not, we have other options to solve the problem, but this would be the most "clean" approach. Thank you!

**Comment by tehnick** [comment]
@32d42eee-2809-41ba-9876-72c2844fcb15
See my detailed reply in mailing list:
https://alioth-lists.debian.net/pipermail/pkg-xmpp-devel/2019-May/003254.html
