### ISSUE TITLE
API change between 2.3.1 and 2.3.2 

### ISSUE THREAD

**Issue by paulfariello** [signalapp/libsignal-protocol-c#125]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
There was a non backward compatible API change between 2.3.1 and 2.3.2. As a developer I didn't attend to see such change in a patch version bump.

What is the current versioning scheme for libsignal-protocol-c?

### Steps to reproduce
- develop something with 2.3.1
- upgrade to 2.3.2
- build failure

**Actual result:** 
```
error: initialization of ‘int (*)(signal_buffer **, signal_buffer **, const signal_protocol_address *, void *)’ {aka ‘int (*)(struct signal_buffer **, struct signal_buffer **, const struct signal_protocol_address *, void *)’} from incompatible pointer type ‘int (*)(signal_buffer **, const signal_protocol_address *, void *)’ {aka ‘int (*)(struct signal_buffer **, const struct signal_protocol_address *, void *)’} [-Werror=incompatible-pointer-types]
         .load_session_func = load_session,
error: initialization of ‘int (*)(const signal_protocol_address *, uint8_t *, size_t,  uint8_t *, size_t,  void *)’ {aka ‘int (*)(const struct signal_protocol_address *, unsigned char *, long unsigned int,  unsigned char *, long unsigned int,  void *)’} from incompatible pointer type ‘int (*)(const signal_protocol_address *, uint8_t *, size_t,  void *)’ {aka ‘int (*)(const struct signal_protocol_address *, unsigned char *, long unsigned int,  void *)’} [-Werror=incompatible-pointer-types]
         .store_session_func = store_session,
```
**Expected result:**
If libsignal-protocol-c were following [semantic versioning](https://semver.org/) I wouldn't have broke build between two patch version.

### Device info
N/A

### Link to logs
N/A

**Comment by dkonigsberg** [comment]
Issue #112 was already opened (and since closed) to complain about this issue. It was an accident, and one I'll be more mindful of in the future.

The original intent of versioning was to try and track the Java version, on a feature basis. However, that ship has long since sailed. Furthermore, this library does sometimes need changes (like this one) that have absolutely nothing to do with the Signal Protocol implementation itself, and are primarily there to handle app integration issues.

**Comment by paulfariello** [comment]
Thanks and sorry for duplicate issue.
