### ISSUE TITLE
Make internal function `session_builder_process_pre_key_signal_message` public?

### ISSUE THREAD

**Issue by hartwork** [signalapp/libsignal-protocol-c#139]
Hi!

In the context of packaging https://github.com/gkdr/lurch for a Linux distribution I noticed that https://github.com/gkdr/axc/ bundles a copy of `libsignal-protocol-c` that I cannot unbundle because [they call](https://github.com/gkdr/axc/blob/206bf43d3e602598db81a083913144ff7089c88d/src/axc.c#L1126) an [internal function `session_builder_process_pre_key_signal_message`](https://github.com/signalapp/libsignal-protocol-c/blob/4a137eaf4eb4421949e2e1dde9f11ec7bc07b88f/src/session_builder_internal.h#L23-L24) for some reason — valid or not.

In the interest of having end-users use a single recent and secure copy of `libsignal-protocol-c` code, I would appreciate your help with

- (a) getting https://github.com/gkdr/axc/ off `session_builder_process_pre_key_signal_message` or
- (b) moving `session_builder_process_pre_key_signal_message` to public API 

so that unbundling becomes possible.

Many thanks in advance,

Sebastian

Related?: #123

**Comment by dkonigsberg** [comment]
The "axc" project appears to completely reimplement the public `session_cipher_decrypt_pre_key_signal_message()` function, which is why they felt the need to call that private function. They shouldn't need to do this, and I'm not sure why they did. Regardless, the library will not be changing to support this behavior.

There have been integrations of this library on a wide variety of platforms, using a wide variety of DB and crypto implementations, and none have needed to poke deeper into the library code than its public interfaces.
