### ISSUE TITLE
Unused field 'device_id' in session_pre_key_bundle

### ISSUE THREAD

**Issue by gkdr** [signalapp/libsignal-protocol-c#55]
I figured this is for legacy reasons, but since you were talking about a to-do list for cleaning up the code in similar issues I think this should go on it as well.

[`session_pre_key_bundle_create()`](https://github.com/WhisperSystems/libsignal-protocol-c/blob/e59089a644ca747ed50442eb8804266618f11c0b/src/session_pre_key.c#L434) takes the parameter `device_id`, which as far as I can tell (Eclipse reference search), is never used.
Especially [`session_builder_process_pre_key_bundle()`](https://github.com/WhisperSystems/libsignal-protocol-c/blob/e59089a644ca747ed50442eb8804266618f11c0b/src/session_builder.c#L191), which seems to be the only function that deals with the bundle, does not use it.
It seems `registration_id` (of proper `uint32_t` instead of just `int`) is used instead.

While not tragic, it creates some confusion about how to properly call `session_pre_key_bundle_create()` and should be included in an overhaul.

(As a sidenote, do you take pull requests with just documentation comments?)

**Comment by dkonigsberg** [comment]
It appears that the explanation here is the same as for the other case you noticed... "Because the Java version has it."

The C library was initially developed with a goal of matching the API of the Java library whenever possible. If you want to know why the Java library does something, you'll need to ask @moxie0 perhaps via the [mailing list](https://lists.riseup.net/www/info/whispersystems).

**Comment by ma11hew28** [comment]
@gkdr great awareness. I just reported the same issue on the Java library. https://github.com/signalapp/libsignal-protocol-java/issues/60
