### ISSUE TITLE
No load_signed_pre_keys in signal_protocol_signed_pre_key_store struct

### ISSUE THREAD

**Issue by drizt** [signalapp/libsignal-protocol-c#67]
libsignal-protocol-java has [SignedPreKeyStore::loadSignedPreKeys](https://github.com/WhisperSystems/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/state/SignedPreKeyStore.java#L29) but libsignal-protocol-c hasn't analogue for such functions.

**Comment by dkonigsberg** [comment]
Do you have a specific use for this function, or are you just looking for API completeness?

It likely wasn't implemented because its something a bit more tedious/cumbersome to provide from a C API than it was from Java, and the library doesn't internally need it.  You can implement something similar in your own code, based on functions the library does expose and information you likely already have access to from within your signed_pre_key_store implementation.

**Comment by drizt** [comment]
The same as in Conversations. I need to know the next available signedPreKeyId. But I agree it's not difficult just implement own function and use it.

**Comment by dkonigsberg** [comment]
The easiest way to do that is to directly query the largest existing signed pre key ID from your actual key store implementation.  Having a callback function/wrapper in the library wouldn't really help you there, and the library itself doesn't need that information internally.

Signal itself does use the mentioned method in one place, as part of a cleanup job that only cares about the list of IDs for which signed pre keys exist.  Having a callback for just the ID list would certainly be easier, but again it doesn't really give you anything more useful than just directly querying this list from your key store implementation.  (It would actually be more work, since you'd have to wrap/unwrap the list from library data types.)
